version: "3.8"

volumes:
    redis_data:
    mongo_data:

services:
  redis:
    container_name: redis_needify
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/prod_data
    networks:
        - the_needify_default
        - the_needify_bot

  mongo_needify:
    image: mongo:6
    container_name: mongo_needify
    restart: always
    volumes:
      - ./Volumes/Mongo:/data/prod_db
    command: mongod --port 27018
    ports:
      - "27018:27018"
    environment:
      MONGO_INITDB_ROOT_USERNAME: needify_root
      MONGO_INITDB_ROOT_PASSWORD: needify_root_password
    networks:
        - the_needify_default
        - the_needify_bot


networks:
  the_needify_default:
    name: needify
  the_needify_bot:
    name: needify_bot