version: '3.8'

volumes:
  static:
  media:
  web-root:


services:
  base_api:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - web-root:/var/www/html
      - .:/usr/src/needify/
    env_file:
      - ./.env
    command: [ "sh", "deploy/entrypoints/run_microservice.sh" ]
    networks:
      - the_needify_default
#    ports:
#      - "8000:8000"
#
#  nginx:
#    build:
#      context: deploy/nginx/
#      dockerfile: Dockerfile
#    ports:
#      - "80:80"
#    depends_on:
#      - base_api
#    networks:
#        - the_needify_default


networks:
  the_needify_default:
    name: needify
  the_needify_bot:
    name: needify_bot
