version: 1
disable_existing_loggers: true

formatters:
  simple:
    class: src.core.logger_settings.CustomColoredFormatter
    format: "%(log_color)s[%(asctime)s] - [%(levelname)8s] - [%(name)7s] - [%(short_context_id)s] - %(message)s"
  file:
    class: src.core.logger_settings.CustomFormatter
    format: "[%(asctime)s] - [%(levelname)8s] - [%(name)7s] - [%(context_id)s] - %(message)s"

handlers:
  telegram:
    class: src.core.logger_settings.TelegramHandler
    level: INFO
    formatter: simple
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  debug:
    class: logging.FileHandler
    level: DEBUG
    formatter: file
    filename: "{logdir}/debug.log"
    encoding: utf8
  error:
    class: logging.FileHandler
    level: ERROR
    formatter: file
    filename: "{logdir}/error.log"
    encoding: utf8

loggers:
  telegram_logger:
    level: INFO
    handlers: [ telegram, debug ]
    propagate: no
  root:
    level: INFO
    handlers: [ debug, console ]
    propagate: no

  root.error:
    level: ERROR
    handlers: [ error ]
    propagate: no

  uvicorn.access:
    level: WARNING
    handlers: [ debug, console ]
    propagate: no

  uvicorn.error:
    level: INFO
    handlers: [ debug, console ]
    formatter: simple
    propagate: no

  LiteClient:
    level: ERROR
    handlers: [ debug, console ]
    propagate: no

  multipart.multipart:
    level: CRITICAL

  passlib:
    level: CRITICAL

  gunicorn.error:
    level: DEBUG
    handlers: [ debug, error ]
    propagate: no

  gunicorn.access:
    level: INFO
    handlers: [ debug, error, console ]
    propagate: yes


