version: '3.8'

volumes:
    redis_data:

services:
  python:
    build:
      context: .
    volumes:
      - ./logs:/usr/src/the_times/logs
    command: python bot.py
    networks:
      - the_times_default

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/prod_data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - the_times_default
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    expose:
      - "6380"

networks:
  the_times_default:
    external: false
